---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: aap
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ansible-automation-platform-operator
  namespace: aap
spec:
  targetNamespaces:
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: aap-catalog-source
  namespace: aap
spec:
  sourceType: grpc
  image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog:v4.10_2023_01_30
  displayName: "Ansible Automation Platform Catalogsource"
  publisher: "Red Hat AgnosticD"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform
  namespace: aap
spec:
  channel: stable-2.3-cluster-scoped
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: aap-catalog-source
  sourceNamespace: aap
